version: "3.9"
services:
  titiler:
    image: developmentseed/titiler
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./:/app:rw
    environment:
      - PORT=8000
      - WORKERS_PER_CORE=1
